CIVDT-964
hmrc/import-voluntary-disclosure-frontend pull request #240
Opened 2021-06-15 09:56 UTC by tvaidotas

2021-06-15 21:12 UTC, macgrewal requested changes
Minor code refactoring suggestions and updating test descriptions but other than that looks good.

2021-06-15 21:12 UTC, macgrewal commented on test/services/submissionService/BuildEntryDetailsSpec.scala
>        "return expect json" in {
```suggestion
      "return expect json for single entry" in {
```

2021-06-15 21:12 UTC, macgrewal commented on test/services/submissionService/BuildReasonsDetailsSpec.scala
>        "return expect json" in {
```suggestion
      "return expect json for a single entry disclosure" in {
```

2021-06-15 21:12 UTC, macgrewal commented on test/services/submissionService/BuildReasonsDetailsSpec.scala
> +      "return expect json in bulk submission" in {
```suggestion
      "return expect json for a bulk entry disclosure" in {
```

2021-06-16 08:26 UTC, tvaidotas commented on app/services/SubmissionService.scala
> +    }
We had it this way but decided that the current way was better, so not sure how to address this...

2021-06-16 10:24 UTC, macgrewal approved these changes

2021-06-16 11:38 UTC, merged