CIVDT-1273: Duplicate Deferment Account Numbers
hmrc/import-voluntary-disclosure-frontend pull request #343
Opened 2021-07-28 10:39 UTC by dannybassi

2021-07-28 14:18 UTC, jacemale-hmrc commented on app/controllers/RepresentativeDanImportVATController.scala
> +        if (sameAccountNumber(dutyAccountNumber, dan.accountNumber, request.userAnswers)) {
I'd probably avoid using `getOrElse` for this,
if we just want to compare the 2 numbers we can do it like
```suggestion
        val dutyAccountNumber = request.userAnswers.get(DefermentAccountPage)
        if (dutyAccountNumber.exists(sameAccountNumber(_, dan.accountNumber, request.userAnswers))) {
```

2021-07-28 14:19 UTC, jacemale-hmrc commented on app/controllers/RepresentativeDanImportVATController.scala
> +    lazy val dutyAccountNumber: String = userAnswers.get(DefermentAccountPage).getOrElse("")
it doesn't need to be lazy
```suggestion
    val dutyAccountNumber: String = userAnswers.get(DefermentAccountPage).getOrElse("")
```

2021-07-28 14:24 UTC, jacemale-hmrc commented on app/controllers/RepresentativeDanImportVATController.scala
> +    )
we don't need `getOrElse` here either`
```suggestion
    val dutyAccountNumber = userAnswers.get(DefermentAccountPage)
    dutyAccountNumber.exists(_ == vatAccountNumber)
```

2021-07-28 14:31 UTC, jacemale-hmrc commented on test/controllers/RepresentativeDanImportVATControllerSpec.scala
> +      controller.onSubmit(request)
this tests seems to submit a request but doesn't verify anything about it (status code or errors etc.)

2021-07-28 14:56 UTC, jacemale-hmrc approved these changes

2021-07-28 15:07 UTC, tvaidotas requested changes
I know it's not your changes per say but would be nice to clean it up a bit

2021-07-28 15:07 UTC, tvaidotas commented on app/controllers/RepresentativeDanImportVATController.scala
> +                }
duplicate, could be refactored into redirect method

2021-07-28 15:07 UTC, tvaidotas commented on app/controllers/RepresentativeDanImportVATController.scala
> +          if (dan.accountNumber != previousVATAccountNumber || dan.danType != previousVATAccountType) {
these two are only used in the if condition below, could call a helper method passing user answers that would return a boolean and just call that in the if statement

2021-07-28 15:07 UTC, tvaidotas commented on app/controllers/RepresentativeDanImportVATController.scala
> +        val dutyAccountNumber = request.userAnswers.get(DefermentAccountPage)
dutyAccountNumber only used in the if statement, could just have it val dutyAccountNumberExists = request.userAnswers.get(DefermentAccountPage).contains(dan.accountNumber)

2021-07-29 09:04 UTC, tvaidotas approved these changes

2021-07-29 10:02 UTC, merged