CIVDT-1376: Introduce an enum for box numbers
hmrc/import-voluntary-disclosure-frontend pull request #377
Opened 2021-08-17 15:54 UTC by jacemale-hmrc

2021-08-18 13:48 UTC, jacemale-hmrc commented on test/controllers/reasons/UnderpaymentReasonAmendmentControllerSpec.scala
> +//    }
I've commented out some tests because the cases they were testing can't happen anymore,
they can all potentially be removed

2021-08-19 09:18 UTC, dannybassi approved these changes

2021-08-19 11:30 UTC, tvaidotas requested changes

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/BoxNumberController.scala
>  import pages.reasons.{UnderpaymentReasonAmendmentPage, UnderpaymentReasonBoxNumberPage, UnderpaymentReasonItemNumberPage, UnderpaymentReasonsPage}
imports

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/BoxNumberController.scala
> +      case BoxNumber.Box22 | BoxNumber.Box62 | BoxNumber.Box63 | BoxNumber.Box66 | BoxNumber.Box67 | BoxNumber.Box68 | BoxNumber.OtherItem =>
could we not import everything from BoxNumber and have the case like Box22 | Box 62 insteaad?

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/BoxNumberController.scala
> +    if (boxNumbers.contains(BoxNumber.OtherItem)) {
similar here have it just as OtherItem

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ChangeUnderpaymentReasonController.scala
>  import play.api.mvc.{Action, AnyContent, Call, MessagesControllerComponents}
import

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ChangeUnderpaymentReasonController.scala
> +    if (underpaymentReason.boxNumber == BoxNumber.OtherItem) {
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ChangeUnderpaymentReasonController.scala
> +      case BoxNumber.OtherItem => messages("changeUnderpaymentReason.otherReasonTitle")
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ChangeUnderpaymentReasonController.scala
> +      case BoxNumber.OtherItem => messages("changeUnderpaymentReason.otherReasonHeading")
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ChangeUnderpaymentReasonDetailsController.scala
> +      case BoxNumber.Box33 | BoxNumber.Box34 | BoxNumber.Box35 | BoxNumber.Box36 | BoxNumber.Box37 | BoxNumber.Box38 | BoxNumber.Box39 |
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ChangeUnderpaymentReasonDetailsController.scala
> +      case BoxNumber.Box22 | BoxNumber.Box37 | BoxNumber.Box39 | BoxNumber.Box41 | BoxNumber.Box42 | BoxNumber.Box62 | BoxNumber.Box63 |
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ConfirmChangeReasonDetailController.scala
> +    val boxNumber = request.userAnswers.get(ChangeUnderpaymentReasonPage).fold(BoxNumber.Box22) { reason =>
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ConfirmReasonDetailController.scala
>  import pages.reasons.{UnderpaymentReasonAmendmentPage, UnderpaymentReasonBoxNumberPage, UnderpaymentReasonItemNumberPage, UnderpaymentReasonsPage}
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ConfirmReasonDetailController.scala
> +    val boxNumber = request.userAnswers.get(UnderpaymentReasonBoxNumberPage).getOrElse(BoxNumber.Box22)
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/ItemNumberController.scala
>  import pages.reasons.{UnderpaymentReasonBoxNumberPage, UnderpaymentReasonItemNumberPage, UnderpaymentReasonsPage}
same

2021-08-19 11:30 UTC, tvaidotas commented on app/controllers/reasons/RemoveUnderpaymentReasonController.scala
> +          if (changeReason.boxNumber == BoxNumber.OtherItem) {
same

2021-08-19 11:36 UTC, tvaidotas approved these changes

2021-08-19 11:37 UTC, merged