CIVDT-1469: Guidance page content update
hmrc/import-voluntary-disclosure-frontend pull request #415
Opened 2021-09-17 14:47 UTC by tvaidotas

2021-09-17 15:06 UTC, jacemale-hmrc commented on app/views/GuidanceView.scala.html
> +                    .
If you place the dot on a new line like this, the rendered HTML will have padding between the text and the dot. Not sure if it's a big issue, but it gets rendered differently.

2021-09-17 15:45 UTC, jacemale-hmrc approved these changes

2021-09-17 15:51 UTC, jakebooker56 approved these changes

2021-09-17 16:45 UTC, ian-ralphs requested changes

2021-09-17 16:45 UTC, ian-ralphs commented on app/views/GuidanceView.scala.html
> +                    If you have any questions or have not received the demand note within 14 days, email
The text is different in the prototype as the comma has been replaced with "then"

2021-09-20 08:18 UTC, tvaidotas commented on app/views/GuidanceView.scala.html
> +            If you are only disclosing underpaid import VAT and use postponed VAT accounting, you should make adjustments on your VAT return to account for the underpaid import VAT. Do not use this s
the link redirects to itself, I asked Jon and he said to just make it normal text until they know where it needs to point

2021-09-20 11:00 UTC, merged