Welsh translation v1
hmrc/import-voluntary-disclosure-frontend pull request #486
Opened 2021-11-30 12:27 UTC by jakebooker56

2021-11-30 14:22 UTC, ian-ralphs requested changes

2021-11-30 14:22 UTC, ian-ralphs commented on app/viewmodels/cya/CYAEntryDetailsSummaryListHelper.scala
> +      val entryMonth = entryDetails.entryDate.getMonth.toString match {
I think you want to use getMonthValue to get the number of the month

2021-11-30 14:22 UTC, ian-ralphs commented on conf/messages.en
> +cya.month.1 = January
given the months could be re-used somewhere else in the app if we wanted I would remove the cya bit and just have it at the tope of the file with the common stuff

2021-11-30 14:49 UTC, ian-ralphs requested changes

2021-11-30 14:49 UTC, ian-ralphs commented on app/viewmodels/cya/CYAEntryDetailsSummaryListHelper.scala
> +      val entryMonth = entryDetails.entryDate.getMonthValue
you don't need to create this temporary variable just use
messages(s"month.${entryDetails.entryDate.getMonthValue}") when building the entryDate

strictly speaking entryDateFormat isn't accurate as the variable contains the entryDate not the Format of it.

2021-12-01 09:39 UTC, dannybassi approved these changes

2021-12-01 09:51 UTC, merged